image: microsoft/dotnet:latest

stages:
  - "Test"
  - "Package"

release:
  stage: "Package"
  script:
    - dotnet publish -r win-x64 -c Release -o ./publish CoreRTHello/CoreRTHello.csproj
  only:
    - master
  artifacts:
    expire_in: 1 week
    paths:
      - publish/