image: microsoft/dotnet:latest

stages:
  - "Test"
  - "Package"

linux-x64:
  stage: "Package"
  script:
    - apt-get update && apt-get install wget
    - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
    - apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-6.0 main"
    - apt-get update
    - apt-get install -y clang-6.0
    - dotnet publish -r linux-x64 -c Release -o ./publish CoreRTHello/CoreRTHello.csproj
  only:
    - master
  artifacts:
    expire_in: 1 week
    paths:
      - publish/

# win-x64:
#   stage: "Package"
#   script:
#     - dotnet publish -r win-x64 -c Release -o ./publish CoreRTHello/CoreRTHello.csproj
#   only:
#     - master
#   artifacts:
#     expire_in: 1 week
#     paths:
#       - publish/