image: microsoft/dotnet:latest

stages:
  - "Test"
  - "Package"

linux-x64:
  stage: "Package"
  script:
    - apt-get update && apt-get install -y clang-3.9
    - dotnet publish -v -r linux-x64 -c Release -o ./publish CoreRTHello/CoreRTHello.csproj
  only:
    - master
  artifacts:
    expire_in: 1 week
    paths:
      - publish/

# win-x64:
#   stage: "Package"
#   script:
#     - dotnet publish -r win-x64 -c Release -o ./publish CoreRTHello/CoreRTHello.csproj
#   only:
#     - master
#   artifacts:
#     expire_in: 1 week
#     paths:
#       - publish/