resources:
- repo: self
queue:
  name: Hosted VS2017
steps:
- powershell: |
   dotnet publish -r win-x64 -c Release -o ./publish CoreRTHello/CoreRTHello.csproj
  displayName: 'PowerShell Script'

- task: PublishPipelineArtifact@0
  displayName: 'Publish Pipeline Artifact'
  inputs:
    artifactName: publish

    targetPath: publish


